<?php
/** @package C9::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("UsersMap.php");

/**
 * UsersDAO provides object-oriented access to the users table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package C9::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class UsersDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Name;

	/** @var string */
	public $Email;

	/** @var string */
	public $Password;

	/** @var string */
	public $RememberToken;

	/** @var timestamp */
	public $CreatedAt;

	/** @var timestamp */
	public $UpdatedAt;



}
?>