


<?php
$servername = "127.0.0.1:3306";
$database = "c9";
$username = "jose_espinheira";
$password = "";
// Create connection
$conn = mysqli_connect($servername, $username, $password, $database);
// Check connection
if (!$conn) {
      die("Connection failed: " . mysqli_connect_error());
}

echo "Connected successfully";

$sql = "
INSERT INTO `cursos` (`id_curso`, `nome`) VALUES (80, 'Engenharia Florestal'),
(79, 'Engenharia geológica'),
(78, 'Engenharia Industrial Madeireira'),
(77, 'Engenharia de manufatura'),
(76, 'Engenharia de Materiais'),
(75, 'Engenharia Mecânica'),
(74, 'Engenharia Mecatrônica'),
(73, 'Engenharia Metalúrgica'),
(72, 'Engenharia Militar'),
(71, 'Engenharia de Minas'),
(70, 'Engenharia Naval e Oceânica'),
(69, 'Engenharia Nuclear'),
(68, 'Engenharia de Pesca'),
(67, 'Engenharia de Petróleo'),
(66, 'Engenharia de Produção'),
(65, 'Engenharia Química'),
(64, 'Engenharia Sanitária'),
(63, 'Engenharia de Sistemas Eletrônicos'),
(62, 'Engenharia de Software'),
(61, 'Engenharia de Tecidos'),
(20, 'Enologia'),
(19, 'Fruticultura'),
(18, 'Gestão de Recursos Hídricos'),
(17, 'Horticultura'),
(16, 'Meliponicultura'),
(15, 'Oftálmica'),
(14, 'Radiologia'),
(13, 'Silvicultura'),
(11, 'Sistemas Biomédicos'),
(12, 'Ciências Exatas'),
(10, 'Bacharelados'),
(9, 'Agronomia (ou Engenharia agronômica)'),
(8, 'Astronomia'),
(7, 'Bioengenharia'),
(6, 'Biofísica'),
(5, 'Ciências Contábeis'),
(4, 'Ciência da Computação'),
(3, 'Ciências Biomoleculares'),
(2, 'Ciências Matemáticas da Terra'),
(264, 'Biologia (licenciatura e bacharelado)'),
(60, 'Engenharia de Telecomunicações'),
(59, 'Engenharia Têxtil'),
(58, 'Estatística'),
(57, 'Farmácia (ou Bioquímica)'),
(56, 'Física (licenciatura e bacharelado)'),
(55, 'Física computacional'),
(54, 'Física médica'),
(53, 'Geofísica'),
(52, 'Geologia'),
(51, 'Geoprocessamento e Sensoriamento Remoto'),
(50, 'Informática (licenciatura e bacharelado)'),
(49, 'Informática biomédica'),
(48, 'Matemática (licenciatura e bacharelado)'),
(47, 'Matemática Aplicada'),
(46, 'Matemática computacional'),
(45, 'Nanotecnologia'),
(44, 'Oceanografia (referido como Ciência dos Mares)'),
(43, 'Química (licenciatura e bacharelado)'),
(42, 'Química ambiental'),
(41, 'Química industrial'),
(263, 'Biologia marinha'),
(262, 'Biomedicina'),
(261, 'Botânica'),
(260, 'Ciências Agrárias'),
(259, 'Ciências Ambientais'),
(258, 'Ciências Biológicas'),
(257, 'Ciências da Saúde'),
(256, 'Ciências do Meio Aquático'),
(255, 'Ecologia'),
(254, 'Educação física (licenciatura e bacharelado)'),
(252, 'Enfermagem'),
(250, 'Fisioterapia'),
(249, 'Fonoaudiologia'),
(40, 'Gerontologia'),
(39, 'Medicina'),
(38, 'Medicina veterinária[4]'),
(37, 'Meteorologia'),
(36, 'Microbiologia e Imunologia'),
(35, 'Naturologia'),
(34, 'Neurociência'),
(33, 'Nutrição'),
(32, 'Odontologia'),
(31, 'Quiropraxia'),
(30, 'Saúde Coletiva'),
(29, 'Terapia ocupacional'),
(28, 'Zootecnia'),
(27, 'Tecnologias'),
(26, 'Aquacultura'),
(25, 'Cafeicultura'),
(24, 'Biotecnologia'),
(23, 'Ciência dos Alimentos'),
(22, 'Cosmetologia'),
(21, 'Drenagem e Irrigação'),
(247, 'Ciências Naturais (licenciatura)'),
(246, 'Ciências Náuticas'),
(245, 'Ciência & Tecnologia'),
(243, 'Educação do Campo (licenciatura)'),
(242, 'Engenharia aeroespacial'),
(241, 'Engenharia aeronáutica'),
(239, 'Engenharia Agrícola'),
(238, 'Engenharia de Alimentos'),
(237, 'Engenharia Ambiental'),
(2361, 'Engenharia biomédica'),
(2351, 'Engenharia Cartográfica (ou Engenharia geográfica)'),
(2331, 'Engenharia Civil'),
(2321, 'Engenharia de Computação'),
(2311, 'Engenharia de controle e automação'),
(2291, 'Engenharia Elétrica (ou Engenharia de Energia)'),
(81, 'Engenharia Física'),
(1228, 'Sistemas de Informação'),
(1227, 'Tecnologias'),
(1226, 'Agrimensura'),
(1225, 'Agroindústria'),
(1224, 'Análise e Desenvolvimento de Sistemas'),
(1223, 'Automação Industrial'),
(1222, 'Biocombustíveis'),
(1221, 'Ciências Aeronáuticas'),
(1220, 'Ciência dos materiais'),
(100, 'Direito'),
(99, 'Economia'),
(98, 'Economia Doméstica'),
(97, 'Editoração'),
(96, 'Educação Artística (licenciatura)'),
(95, 'Escultura'),
(94, 'Filosofia (licenciatura e bacharelado)'),
(93, 'Gastronomia'),
(92, 'Geografia (licenciatura e bacharelado)'),
(91, 'Gestão Ambiental'),
(90, 'Gestão Pública'),
(89, 'Gravurismo'),
(88, 'História (licenciatura e bacharelado)'),
(87, 'História da Arte'),
(86, 'Hotelaria'),
(85, 'Jornalismo'),
(84, 'Letras[28] (licenciatura e bacharelado)'),
(83, 'Linguística'),
(82, 'Museologia'),
(1219, 'Construção de Edifícios'),
(1218, 'Construção de Estradas'),
(1215, 'Construção Naval'),
(1212, 'Energias Renováveis'),
(1211, 'Gestão da Tecnologia da Informação'),
(1210, 'Gestão de Petróleo e Gás'),
(1208, 'Gestão Portuária'),
(1207, 'Manutenção Industrial'),
(1123, 'Administração'),
(1122, 'Antropologia'),
(1121, 'Arqueologia'),
(1120, 'Arquitetura'),
(1119, 'Arquivística'),
(1117, 'Artes Cênicas (licenciatura e bacharelado)'),
(1116, 'Artes Visuais (licenciatura e bacharelado)'),
(1115, 'Biblioteconomia'),
(1114, 'Ciências Atuariais'),
(1113, 'Ciências Contábeis'),
(1112, 'Ciências Humanas (licenciatura)'),
(1111, 'Ciência Política (ou Ciências do Estado)'),
(1110, 'Ciências Sociais'),
(1109, 'Cinema'),
(1107, 'Comunicação social'),
(1105, 'Dança (licenciatura e bacharelado)'),
(104, 'Defesa e Gestão Estratégica Internacional'),
(103, 'Desenho Industrial'),
(102, 'Design de Interiores'),
(101, 'Design de Moda'),
(1205, 'Mecatrônica e Mecânica de Precisão'),
(1203, 'Mineração'),
(1202, 'Processos Metalúrgicos'),
(1201, 'Processamento de Dados'),
(141, 'Produção de Laticínios'),
(140, 'Produção de Materiais Plásticos'),
(139, 'Produção Têxtil'),
(138, 'Produção Sucroalcooeira'),
(137, 'Projetos de Estruturas Aeronáuticas'),
(136, 'Redes de Computadores'),
(135, 'Redes de Telecomunicações'),
(134, 'Saneamento Ambiental'),
(133, 'Segurança da Informação'),
(132, 'Sistemas Biomédicos'),
(131, 'Sistemas Elétricos'),
(129, 'Sistemas Embarcados'),
(128, 'Sistemas de Navegação Fluvial'),
(127, 'Sistemas para Internet'),
(126, 'Telemática'),
(125, 'Ciências Humanas'),
(124, 'Bacharelados'),
(1163, 'Gestão Hospitalar'),
(1161, 'Gestão de Segurança Privada'),
(1160, 'Gestão da Qualidade'),
(1159, 'Logística'),
(1158, 'Mercadologia'),
(1157, 'Negócios Imobiliários'),
(1156, 'Processos Escolares'),
(1155, 'Produção de Aguardente[32]'),
(1154, 'Produção Fonográfica'),
(1153, 'Recursos Humanos'),
(1152, 'Secretariado'),
(1151, 'Segurança no Trabalho'),
(1150, 'Transporte Aéreo'),
(1149, 'Gestão em serviços jurídicos e notariais'),
(1200, 'Música (licenciatura e bacharelado)'),
(1199, 'Ordenamento do Território'),
(1197, 'Paisagismo'),
(1196, 'Pedagogia (licenciatura e bacharelado)'),
(1193, 'Pintura'),
(1192, 'Psicologia'),
(1191, 'Publicidade & Propaganda'),
(1190, 'Produção Audiovisual (referido como Rádio & TV)'),
(1189, 'Produção Cultural'),
(1188, 'Relações Internacionais'),
(1187, 'Relações Públicas'),
(1186, 'Segurança Pública'),
(1185, 'Serviço Social'),
(1184, 'Sociologia (licenciatura e bacharelado)'),
(1183, 'Teatro (licenciatura e bacharelado)'),
(181, 'Teologia'),
(180, 'Transporte Terrestre'),
(179, 'Turismologia'),
(178, 'Urbanismo'),
(177, 'Tecnologias'),
(176, 'Agroecologia'),
(175, 'Comércio Exterior'),
(174, 'Cooperativismo'),
(173, 'Design de Jogos Digitais'),
(172, 'Design de produto'),
(171, 'Design gráfico'),
(170, 'Eventos'),
(169, 'Esporte e Lazer'),
(168, 'Fotografia'),
(167, 'Gestão do Agronegócio'),
(166, 'Gestão Comercial'),
(165, 'Gestão Financeira');

";
if (mysqli_query($conn, $sql)) {
      echo "New record created successfully";
} else {
      echo "Error: " . $sql . "<br>" . mysqli_error($conn);
}
mysqli_close($conn);
?>